name: Check Build

on: 
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'
  pull_request:
    branches: [ develop ]
    paths-ignore: 
      - '**.md'

jobs:
  test:
    name: Test - Build & Unit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup - Java
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.x
          distribution: 'adopt'

      - name: Setup - Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-  

      - name: Build - Gradle
        run: ./gradlew build
