name: Develop CI

on: 
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test - Build & Unit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup - Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      - name: Setup - Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-  

      - name: Build - Gradle
        run: ./gradlew build
