name: Develop CI

on: 
  push:
    branches: 
      - 'develop'

jobs:
  test:
    name: Test - Build & Unit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup - Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Setup - Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-  
      - name: Build - Gradle
        run: ./gradlew build
