name: Master CI

on: 
  push:
    branches: 
      - 'master'

# Don't use a cache here: 
#  This is the last instance that can detect missing dependecies

jobs:
  build_release:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup - Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Build - Gradle
        run: ./gradlew build
      - name: Release - Create Draft for Release
        id: create_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release - Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_draft.outputs.upload_url }} 
          asset_path: ./build/libs/avesflower.jar
          asset_name: avesflower.jar
          asset_content_type: application/java-archive
