name: Pull detached upstream automatically

on:
  schedule:
    # Run once per day
    - cron: '22 2 * * *'
  
jobs:
  check_upstream:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      # Checkout this repo
      - uses: actions/checkout@v2
      # Fetch the history and unshallow the checked out repo so that it can be used
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      # Pull the detached remote and do the magic
      - name: Pull Detached Remote
        uses: litetex/pull-detached-remote@v0.1.2
        with:
          upstreamrepo: https://github.com/fesh0r/fernflower
          upstreambranch: master
        env:
          # NOTE: This is a Personal Access Token, ${{ secrets.GITHUB_TOKEN }} has not enough permissions :(
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
